import Header from "./components/Header";
import "./globals.css";
import { Inter, Noto_Sans_Mono } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const noto = Noto_Sans_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
